[package]
name = "Fractal-Generator"
version = "0.1.0"
authors = ["Simon Barton <simon5@pdx.edu>", "Liam Rotchford <rliam@pdx.edu>"]
edition = "2018"

[dependencies]
num = "0.1.27"
image = "0.13.0"
crossbeam = "0.2.8"
